[package]
name = "dogwalker"
version = "0.1.0"
edition = "2021"
default-run = "dogwalker"

[dependencies]
quickperm = { git = "https://github.com/yescallop/quickperm-rs" }
rand = { version = "0.8.5", features = ["small_rng"] }
