[package]
name = "dogwalker"
version = "0.1.0"
edition = "2021"

[dependencies]
ctrlc = "3"
mixhash = { git = "https://github.com/yescallop/mixhash" }
quickperm = { git = "https://github.com/yescallop/quickperm-rs" }
readonly = "0.2"
